config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
	get 'status' => 'home#index', :as => 'status'
	
	get 'login' => 'session#new', :as => 'login'
	post 'create_session' => 'session#create', :as => 'create_session'
	get 'logout' => 'session#destroy', :as => 'logout'
	
	
	get 'settings' => 'admin#settings', :as => 'settings'
	post 'save_settings' => 'admin#save_settings', :as => 'save_settings'
	post 'create_alert_email' => 'admin#create_alert_email', :as => 'create_alert_email'
	delete 'delete_alert_email/:id' => 'admin#delete_alert_email', :as => 'delete_alert_email'
	get 'send_test_email' => 'admin#send_test_email', :as => 'send_test_email'
	post 'save_token' => 'admin#save_token', :as => 'save_token'
	
	get 'index_plot' => 'editor#index_plot', :as => 'index_plot'
	get 'index_box' => 'editor#index_box', :as => 'index_box'
	get 'index_alert' => 'editor#index_alert', :as => 'index_alert'
	
	get 'new_plot' => 'editor#new_plot', :as => 'new_plot'
	get 'new_box' => 'editor#new_box', :as => 'new_box'
	get 'new_alert' => 'editor#new_alert', :as => 'new_alert'
	
	get 'edit_plot/:id' => 'editor#edit_plot', :as => 'edit_plot'
	get 'edit_box/:id' => 'editor#edit_box', :as => 'edit_box'
	get 'edit_alert/:id' => 'editor#edit_alert', :as => 'edit_alert'
	
	post 'update_plot/:id' => 'editor#update_plot', :as => 'update_plot'
	post 'update_box/:id' => 'editor#update_box', :as => 'update_box'
	post 'update_alert/:id' => 'editor#update_alert', :as => 'update_alert'
	
 	post 'create_plot' => 'editor#create_plot', :as => 'create_plot'
 	post 'create_box' => 'editor#create_box', :as => 'create_box'
 	post 'create_alert' => 'editor#create_alert', :as => 'create_alert'
 	
 	delete 'delete_plot/:id' => 'editor#delete_plot', :as => 'delete_plot'
 	delete 'delete_box/:id' => 'editor#delete_box', :as => 'delete_box'
 	delete 'delete_alert/:id' => 'editor#delete_alert', :as => 'delete_alert'
 	
 	delete 'reset_plots' => 'editor#reset_plots', :as => 'reset_plots'
  delete 'reset_boxes' => 'editor#reset_boxes', :as => 'reset_boxes'
  delete 'reset_alerts' => 'editor#reset_alerts', :as => 'reset_alerts'
end

app/models/alert.rb
class Alert < ActiveRecord::Base

	validates_presence_of :query, :label, :message

	#
	# Returns true when this alert should send out a notification.
	#   A notification should be sent when the first 
	#
	def trigger?
	
		# Check if we already notified on this alert more recently than 
		#   settings.repeat_notification_after_seconds
		
		return false if Notification.where("alert_id = ?", self.id)
																.where("created_at > ?", Time.now - Setting.first.repeat_notification_after_seconds.seconds)
																.first.present?
		
		# Check notification condition
		result = ActiveRecord::Base.connection.execute self.query
		
		return true if result.blank? || result.first.blank? || result.first.keys.blank? || result.first[result.first.keys.first].blank?
		return false
	end

end

app/models/alert_email.rb
class AlertEmail < ActiveRecord::Base

	validates_presence_of :email
	validates_uniqueness_of :email
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

end

app/models/box.rb
class Box < ActiveRecord::Base

	validates_presence_of :query, :label

	#
	# Returns the first value from the query associated with the box.
	#
	def metric_value
		result = ActiveRecord::Base.connection.execute self.query
		return nil if result.blank? || result.first.blank? || result.first.keys.blank?
		return result.first[result.first.keys.first] # is there a better way to do this?
	end

end

app/models/column.rb
class Column < ActiveRecord::Base
end

app/models/database.rb
class Database < ActiveRecord::Base
end

app/models/filesystem.rb
class Filesystem < ActiveRecord::Base
end

app/models/function.rb
class Function < ActiveRecord::Base
end

app/models/heartbeat.rb
class Heartbeat < ActiveRecord::Base
end

app/models/index.rb
class Index < ActiveRecord::Base
end

app/models/notification.rb
class Notification < ActiveRecord::Base
end

app/models/plot.rb
class Plot < ActiveRecord::Base

	validates_presence_of :query, :title, :width, :height

	CONTAINER_WIDTH = 1140

	def svg
	  
	  # 1140px style width of home display page.
	  #   kind of janky to relative sizes, waiting to see how this shakes out.
	  #
	  #  Consider: static height.
	  #    Consider: height px, width %
	  
	  width_pixels = ([self.width, 100].min / 100.0) * CONTAINER_WIDTH
	  
	  plot_query = PLOT_DEFAULTS
		plot_query += "set plotpg.terminal='svg size #{width_pixels}, #{self.height}';"
		plot_query += "select plot('#{self.query.gsub(/'/, "''")}'"
		if self.gnuplot_commands.present?
			gnuplot_cmds = "set title '#{self.title}';".gsub(/'/, "''")
			gnuplot_cmds += self.gnuplot_commands.gsub(/'/, "''")
			plot_query += ", '#{gnuplot_cmds}'"
		end
		plot_query += ")"
		
		plot = ActiveRecord::Base.connection.execute plot_query
		svg_string = plot.first["plot"]
		
		return svg_string
	end
	
	# This comment contains an example of a technique for adjusting the width of the svg
	#   returned from the query.  IT's still up in the air how to best handle forming
	#   the svg for the web.
	# x = Nokogiri::HTML(svg_string)		
	# x.xpath('//svg').first['width'] = "#{self.width.to_i}%"
	
	
	#
	# Execute the query and return tabular data
	#
	def data
	end
	
end

app/models/restart_guc.rb
class RestartGuc < ActiveRecord::Base
end

app/models/setting.rb
class Setting < ActiveRecord::Base

end

app/models/stat_class.rb
class StatClass < ActiveRecord::Base
	self.table_name = 'stat_class'
end

app/models/stat_column.rb
class StatColumn < ActiveRecord::Base
	self.table_name = 'stat_column'
end

app/models/stat_lock.rb
class StatLock < ActiveRecord::Base
	self.table_name = 'stat_lock'
end

app/models/stat_system.rb
class StatSystem < ActiveRecord::Base
end

app/models/statement.rb
class Statement < ActiveRecord::Base
end

app/models/table.rb
class Table < ActiveRecord::Base
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/settings.html.erb
<%= form_tag save_token_path do %>
	<h4>Access Token</h4>
	
	<p>If populated, the access token will be required to view the pgantenna page.  This is light weight security intended for basic access control.</p>
		
	<table class="form_table">
	  <tr>
	    <td>
				<div class="form-group" style="width: 300px;">
				  <% message = "Access Token" %>
				  <% message = "Set New Access Token" if @settings.access_token.present? %>
					<%= password_field_tag :access_token, '', :class => 'form-control', :placeholder => message %>
				</div>
			</td>
		</tr>
	</table>
	<%= submit_tag 'Set Access Token', :class => 'btn btn-primary' %>
	
	<hr/>
<% end %>	

<%= form_tag save_settings_path do %>
	<h4>Email Configuration</h4>
	
	<p>
		To enable email alerting please enter AWS SES information below.
	</p>
	
	<table class="form_table">
	  <tr>
	    <td>
				<div class="form-group" style="width: 400px;">
					<label class="control-label" for="focusedInput">SES Secret Key</label>
					<%= text_field_tag :ses_secret_key, @settings.ses_secret_key, :class => 'form-control' %>
				</div>
			</td>
		</tr>
		<tr>
	    <td>
				<div class="form-group" style="width: 400px;">
					<label class="control-label" for="focusedInput">SES Access Key</label>
					<%= text_field_tag :ses_access_key, @settings.ses_access_key, :class => 'form-control' %>
				</div>
			</td>
		</tr>
		<tr>
	    <td>
				<div class="form-group" style="width: 400px;">
					<label class="control-label" for="focusedInput">Sender Email Address</label>
					<%= text_field_tag :ses_from_email, @settings.ses_from_email, :class => 'form-control' %>
				</div>
			</td>
		</tr>
		<tr>
	    <td>
				<div class="form-group" style="width: 400px;">
					<label class="control-label" for="focusedInput">Delay in Seconds Between Repeated Alerts</label>
					<%= text_field_tag :repeat_notification_after_seconds, @settings.repeat_notification_after_seconds, :class => 'form-control' %>
				</div>
			</td>
		</tr>
	</table>
	
	<%= submit_tag 'Save Settings', :class => 'btn btn-primary' %>&nbsp;&nbsp;
	<% if @settings.ses_from_email.present? && @settings.ses_access_key.present? && @settings.ses_secret_key.present? && @alert_emails.length > 0 %>
	  <%= link_to 'Send Test Email', send_test_email_path, :class => 'btn btn-info' %>
	<% end %>

<% end %>
<br/><br/>
<h4> Alert Emails </h4>
<p>An email will be sent to the following email addresses when an alert event is detected.</p>

<%= form_tag create_alert_email_path do %>
	<table class="form_table table table-striped table-hover config-table">
		<% @alert_emails.each do |ae| %>
			<tr>
				<td>
					<%= ae.email %>
				</td>
				<td class="last">
					<%= link_to 'Delete',  delete_alert_email_path(ae.id),  style: 'float: right;', method: :delete, data: { confirm: 'Are you sure?' } %>
				</td>
			</tr>
		<% end %>
	</table>
	<table class="admin_control_form_table">
		<tr>
			<td><br/>
				<%= text_field_tag :email, '', :class => 'form-control', :placeholder => 'Email address to be alerted', :size => 35 %>
			</td>
			<td class="last">
				<br/>
				<%= submit_tag 'Add Email Address', :class => 'btn btn-success' %>
			</td>
		</tr>
	</table>
<% end %>

<br/><br/><br/>

app/views/layouts/_flash_message.html.erb
<% if flash[:notice] %>
  <div class="alert alert-warning">
    <%= flash[:notice].html_safe %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<% if !@suppress_navbar %>
	<div class="navbar navbar-default navbar-head">
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		    <span class="icon-bar"></span>
		  </button>
		</div>
		<div class="navbar-collapse collapse navbar-responsive-collapse">
		  
		  <ul class="nav navbar-nav"> 
		    <li>
		    	<%= link_to 'Status', status_path %>
		    </li>
		  </ul>		

		  <ul class="nav navbar-nav navbar-right">
		 		<% if @current_connection.present? %>
		 		  <li>
		      <span class="connected_message">Client connected: <%= @current_connection.ip %></span>
		      </li>
		    <% end %>
		    <li class="dropdown">
		      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <b class="caret"></b></a>
		      <ul class="dropdown-menu">
		        <li><%= link_to 'Configure Box Stats', index_box_path %></li>
		        <li><%= link_to 'Configure Plots', index_plot_path %></li>
		        <li><%= link_to 'Configure Alerts', index_alert_path %></li>
		        <li class="divider"></li>
		        <li><%= link_to 'Settings', settings_path %></li>
		        <% if session[:valid].present? %>
				      <li class="divider"></li>
				      <li><%= link_to 'Sign Out', logout_path %></li>
		        <% end %>
		      </ul>
		    </li>
		  </ul>
		</div>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pgantenna</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <% if @include_ace %>
	  <%= javascript_include_tag 'ace/ace', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'ace/mode-pgsql', 'data-turbolinks-track' => true %>
  <% end %>
  
</head>
<body>

  <div class="container">

  	<%= render 'layouts/navbar' %>
  	<%= render 'layouts/flash_message' %>
  	
		<%= yield %>
  </div>
</body>
</html>