config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
	get 'status' => 'home#index', :as => 'status'
	
	get 'login' => 'session#new', :as => 'login'
	post 'create_session' => 'session#create', :as => 'create_session'
	get 'logout' => 'session#destroy', :as => 'logout'
	
	
	get 'settings' => 'admin#settings', :as => 'settings'
	post 'save_settings' => 'admin#save_settings', :as => 'save_settings'
	post 'create_alert_email' => 'admin#create_alert_email', :as => 'create_alert_email'
	delete 'delete_alert_email/:id' => 'admin#delete_alert_email', :as => 'delete_alert_email'
	get 'send_test_email' => 'admin#send_test_email', :as => 'send_test_email'
	post 'save_token' => 'admin#save_token', :as => 'save_token'
	
	get 'index_plot' => 'editor#index_plot', :as => 'index_plot'
	get 'index_box' => 'editor#index_box', :as => 'index_box'
	get 'index_alert' => 'editor#index_alert', :as => 'index_alert'
	
	get 'new_plot' => 'editor#new_plot', :as => 'new_plot'
	get 'new_box' => 'editor#new_box', :as => 'new_box'
	get 'new_alert' => 'editor#new_alert', :as => 'new_alert'
	
	get 'edit_plot/:id' => 'editor#edit_plot', :as => 'edit_plot'
	get 'edit_box/:id' => 'editor#edit_box', :as => 'edit_box'
	get 'edit_alert/:id' => 'editor#edit_alert', :as => 'edit_alert'
	
	post 'update_plot/:id' => 'editor#update_plot', :as => 'update_plot'
	post 'update_box/:id' => 'editor#update_box', :as => 'update_box'
	post 'update_alert/:id' => 'editor#update_alert', :as => 'update_alert'
	
 	post 'create_plot' => 'editor#create_plot', :as => 'create_plot'
 	post 'create_box' => 'editor#create_box', :as => 'create_box'
 	post 'create_alert' => 'editor#create_alert', :as => 'create_alert'
 	
 	delete 'delete_plot/:id' => 'editor#delete_plot', :as => 'delete_plot'
 	delete 'delete_box/:id' => 'editor#delete_box', :as => 'delete_box'
 	delete 'delete_alert/:id' => 'editor#delete_alert', :as => 'delete_alert'
 	
 	delete 'reset_plots' => 'editor#reset_plots', :as => 'reset_plots'
  delete 'reset_boxes' => 'editor#reset_boxes', :as => 'reset_boxes'
  delete 'reset_alerts' => 'editor#reset_alerts', :as => 'reset_alerts'
end

app/controllers/editor_controller.rb
#
# This controller provides endpoints for adding, deleting, and editing box stat 
#   and plot records.  These are the actual monitoring information displayed on 
#   the status page.
#
# Box Stats are queries where the first row/column entry in the result set
#   are displayed as a single number. 
#
# Plots are queries that are passed to the plot() function from provided by the
#   plotpg library.
#
# Alerts are queries such that if the first field in the first row is true, then
#   an alert action will be triggered, sending emails to all configured alert emails.
#
class EditorController < ApplicationController

	def index_box
		@boxes = Box.all
	end
	
	def index_plot
		@plots = Plot.all
	end
	
	def index_alert
		@alerts = Alert.all
	end

	def new_plot
		@include_ace = true
		@plot = Plot.new
	end
	
	def new_box
		@include_ace = true
		@box = Box.new
	end
	
	def new_alert
		@include_ace = true
		@alert = Alert.new
	end
	
	def edit_plot
		@include_ace = true
		@plot = Plot.find params[:id]
	end
	
	def edit_box
		@include_ace = true
		@box = Box.find params[:id]
	end
	
	def edit_alert
		@include_ace = true
		@alert = Alert.find params[:id]
	end
	
	def update_plot
		p = Plot.find params[:id]
		if p.update_attributes(:title => params[:title],
												:query => params[:query],
												:height => params[:height],
												:width => params[:width],
												:gnuplot_commands => params[:gnuplot_commands])
			flash[:notice] = "Plot updated"
			redirect_to index_plot_path
		else
			flash[:notice] = p.errors.to_a.join(", ").to_s
			redirect_to edit_plot_path(p.id)
		end
	end
	
	def update_box
		b = Box.find params[:id]
		if b.update_attributes(:label => params[:label],
													 :query => params[:query])
			flash[:notice] = "Box updated"
			redirect_to index_box_path
		else
			flash[:notice] = b.errors.to_a.join(", ").to_s
			redirect_to edit_box_path(b.id)
		end

	end
	
	def update_alert
		a = Alert.find params[:id]
		if a.update_attributes(:label => params[:label],
												:query => params[:query],
												:message => params[:message])
			flash[:notice] = "Alert updated"
			redirect_to index_alert_path
		else
			flash[:notice] = a.errors.to_a.join(", ").to_s
			redirect_to edit_alert_path(a.id)
		end
	end

	def create_plot	
		p = Plot.create(:title => params[:title],
										:query => params[:query],
										:height => params[:height],
										:width => params[:width],
										:gnuplot_commands => params[:gnuplot_commands])
		if p.id.present?
			flash[:notice] = "Plot created"
			redirect_to index_plot_path
		else
			flash[:notice] = p.errors.to_a.join(", ").to_s
			redirect_to new_plot_path
		end
	end
	
	def create_box
		b = Box.create(:label => params[:label],
									:query => params[:query])
		if b.id.present?
			flash[:notice] = "Box created"
			redirect_to index_box_path
		else
			flash[:notice] = b.errors.to_a.join(", ").to_s
			redirect_to new_box_path
		end
	end
	
	def create_alert
		a = Alert.create(:label => params[:label],
									:query => params[:query],
									:message => params[:message])
		if a.id.present?
			flash[:notice] = "Alert created"
			redirect_to index_alert_path
		else
			flash[:notice] = a.errors.to_a.join(", ").to_s
			redirect_to new_alert_path
		end
	end
	
	def delete_plot
		@plot = Plot.find params[:id]
		@plot.delete
		redirect_to index_plot_path
	end
	
	def delete_box
		@box = Box.find params[:id]
		@box.delete
		redirect_to index_box_path
	end
	
	def delete_alert
		@box = Alert.find params[:id]
		@box.delete
		redirect_to index_alert_path
	end

	def reset_boxes
		Reset.boxes!
		redirect_to index_box_path
	end
	
	def reset_plots
		Reset.plots!
		redirect_to index_plot_path
	end
	
	def reset_alerts
		Reset.alerts!
		redirect_to index_alert_path
	end

end

app/helpers/editor_helper.rb
module EditorHelper
end

app/views/editor/_ace.html.erb
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/vibrant_ink");
    editor.getSession().setMode("ace/mode/pgsql");
    
    
    var textarea = $('textarea[name="query"]');
		editor.getSession().on("change", function () {
				textarea.val(editor.getSession().getValue());
		});
    
</script>

app/views/editor/edit_alert.html.erb
<%= form_tag update_alert_path, :class => 'bs-component' do %>
	
	<table class="form_table">
	  <tr>
	    <td>
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Label</label>
					<%= text_field_tag 'label', @alert.label, :class => 'form-control' %>
				</div>
			</td>
		</tr>
		<tr>
	    <td>
				<div class="form-group" style="width: 700px;">
					<label class="control-label" for="focusedInput">Message</label>
					<%= text_field_tag 'message', @alert.message, :class => 'form-control' %>
				</div>
			</td>
		</tr>
	</table>

	<table class="form_table">
	  <tr> 
	    <td>
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Alert Query</label>
					<div id="editor"><%= @alert.query %></div>
				</div>
			</td>
		</tr>
		<tr>
		  <td>
		  	The alert query will be evaluated, and if the first cell in the result set exists and is not null, then an email will be sent to each <%= link_to 'configured alert_email', settings_path %>.  <a href="https://github.com/no0p/pgantenna/wiki/Customizing-Alerts">Alerts Guide</a>
		  </td>
		</tr>
	</table>

	<%= hidden_field_tag :id, @alert.id %>
  <textarea name="query" style="display: none;">
  	<%= @alert.query %>
  </textarea>
	<br/>
  <%= submit_tag 'Save Alert Changes', :class => 'btn btn-primary' %>

<% end %>



<%= render 'ace' %>

app/views/editor/edit_box.html.erb
<%= form_tag update_box_path, :class => 'bs-component' do %>
	
	<table class="form_table">
	  <tr>
	    <td>
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Label</label>
					<%= text_field_tag 'label', @box.label, :class => 'form-control' %>
				</div>
			</td>
		</tr>
	</table>

	<table class="form_table">
	  <tr> 
	    <td>
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Box Stat Query</label>
					<div id="editor"><%= @box.query %></div>
				</div>
			</td>
		</tr>
		<tr>
		  <td>
		  	The box query will be evaluated and the first cell in the result set will be displayed in the box. For information on the statistics tables created please see the <a href="https://github.com/no0p/plotpg">pgantenna statistics tables reference guide.
		  </td>
		</tr>
	</table>

	<%= hidden_field_tag :id, @box.id %>
  <textarea name="query" style="display: none;">
  	<%= @box.query %>
  </textarea>
	<br/>
  <%= submit_tag 'Save Plot Changes', :class => 'btn btn-primary' %>

<% end %>



<%= render 'ace' %>

app/views/editor/edit_plot.html.erb
<%= form_tag update_plot_path, :class => 'bs-component' do %>
	
	<table class="form_table">
	  <tr>
	    <td>
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Title</label>
					<%= text_field_tag 'title', @plot.title, :class => 'form-control' %>
				</div>
			</td>
		</tr>
	</table>
	
	<table class="form_table">
	  <tr> 
	    <td>
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Width (% of row)</label>
					<%= text_field_tag 'width', @plot.width, :class => 'form-control' %>
				</div>
			</td>
			<td class="last">	
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Height (pixels)</label>
					<%= text_field_tag 'height', @plot.height, :class => 'form-control' %>
				</div>
			</td>
		</tr>
	</table>

	<table class="form_table">
	  <tr> 
	    <td>
				<div class="form-group" style="">
					<label class="control-label" for="focusedInput">Plot Query</label><br/>
					<span class="form_message">The plot query is passed to the <a href="https://github.com/no0p/plotpg">plotpg</a> function, and the resulting chart is displayed.</span><br/><br/>
					<div id="editor"><%= @plot.query %></div>
				</div>
			</td>
		</tr>
	</table>

	<table class="form_table">
	  <tr> 
	    <td>
				<div class="form-group" style="">
					<label class="control-label" for="focusedInput">Gnuplot Commands</label><br/>
					<span class="form_message">Optional commands that are passed as the second parameter to the <a href="https://github.com/no0p/plotpg/wiki/Plotting-Data">plot function</a>.</span><br/><br/>
					<textarea name="gnuplot_commands" class="form-control" rows="5"><%= @plot.gnuplot_commands %></textarea>
				</div>
			</td>
		</tr>
	</table>


	<%= hidden_field_tag :id, @plot.id %>
  <textarea name="query" style="display: none;">
  	<%= @plot.query %>
  </textarea>
	<br/>
  <%= submit_tag 'Save Plot Changes', :class => 'btn btn-primary' %>

<% end %>



<%= render 'ace' %>

app/views/editor/index_alert.html.erb
<h4>Alerts</h4>
<br/>

<table class="table table-striped table-hover config-table">

  <tbody>
		<% @alerts.each do |p| %>
			<tr>
			  <td>
			    <%= p.label %>
			  </td>
			
			  <td>
			    <div class="action_links">
					  <%= link_to 'Edit', edit_alert_path(p) %>
					  &nbsp;
					  <%= link_to 'Delete',  delete_alert_path(p.id),  method: :delete, data: { confirm: 'Are you sure?' } %>
					</div>
			  </td>
			</tr>
		<% end %>
	</tbody>
</table>

<br/>

<div class="main_action_row">
  <%= link_to '+ Add new alert', new_alert_path, :class => 'edit_link' %> 
  &nbsp;&nbsp;&nbsp;
  <%= link_to 'Reset Defaults',  reset_alerts_path, class: 'edit_link last_link', method: :delete, data: { confirm: 'Are you sure?  This will delete all alerts and restore to default alerts.' } %>
</div>

app/views/editor/index_box.html.erb
<h4>Box Displays</h4>
<br/>

<table class="table table-striped table-hover config-table">

  <tbody>
		<% @boxes.each do |p| %>
			<tr>
			  <td>
			    <%= p.label %>
			  </td>
			
			  <td>
			    <div class="action_links">
					  <%= link_to 'Edit', edit_box_path(p) %>&nbsp;
					  <%= link_to 'Delete',  delete_box_path(p.id),  method: :delete, data: { confirm: 'Are you sure?' } %>
					</div>
			  </td>
			</tr>
		<% end %>
	</tbody>
</table>

<br/>

<div class="main_action_row">
  <%= link_to '+ Add new box', new_box_path, :class => 'edit_link' %> 
  &nbsp;&nbsp;&nbsp;
  <%= link_to 'Reset Defaults',  reset_boxes_path, class: 'edit_link last_link', method: :delete, data: { confirm: 'Are you sure?  This will delete all boxs and restore to default boxes.' } %>
</div>

app/views/editor/index_plot.html.erb
<h4>Plot Displays</h4>
<br/>

<table class="table table-striped table-hover config-table">

  <tbody>
		<% @plots.each do |p| %>
			<tr>
			  <td>
			    <%= p.title %>
			  </td>
			
			  <td>
			    <div class="action_links">
					  <%= link_to 'Edit', edit_plot_path(p) %>&nbsp;
					  <%= link_to 'Delete',  delete_plot_path(p.id),  method: :delete, data: { confirm: 'Are you sure?' } %>
					</div>
			  </td>
			</tr>
		<% end %>
	</tbody>
</table>

<br/>

<div class="main_action_row">
  <%= link_to '+ Add new plot', new_plot_path, :class => 'edit_link' %> 
  &nbsp;&nbsp;&nbsp;
  <%= link_to 'Reset Defaults',  reset_plots_path, class: 'edit_link last_link', method: :delete, data: { confirm: 'Are you sure?  This will delete all plots and restore to default plots.' } %>
</div>

app/views/editor/new_alert.html.erb
<%= form_tag create_alert_path, :class => 'bs-component' do %>
	
	<table class="form_table">
	  <tr>
	    <td>
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Label</label>
					<%= text_field_tag 'label', @alert.label, :class => 'form-control', :placeholder => 'Alert name' %>
				</div>
			</td>
		</tr>
		<tr>
	    <td>
				<div class="form-group" style="width: 700px;">
					<label class="control-label" for="focusedInput">Message</label>
					<%= text_field_tag 'message', @alert.message, :class => 'form-control', :placeholder => 'The alert message will be the email body' %>
				</div>
			</td>
		</tr>
	</table>

	<table class="form_table">
	  <tr> 
	    <td>
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Alert Query</label>
					<div id="editor"></div>
				</div>
			</td>
		</tr>
		<tr>
		  <td>
		  	The alert query will be evaluated, and if the first cell in the result set exists and is not null, then an email will be sent to each <%= link_to 'configured alert_email', settings_path %>.  <a href="https://github.com/no0p/pgantenna/wiki/Customizing-Alerts">Alerts Guide</a>
		  </td>
		</tr>
	</table>

  <textarea name="query" style="display: none;">
  </textarea>
	<br/>
  <%= submit_tag 'Create Alert', :class => 'btn btn-primary' %>

<% end %>



<%= render 'ace' %>

app/views/editor/new_box.html.erb
<h4>Create New Stat Box</h4>
<br/><br/>

<%= form_tag create_box_path, :class => 'bs-component' do %>
	
	<table class="form_table">
	  <tr>
	    <td>
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Label</label>
					<%= text_field_tag 'label', @box.label, :class => 'form-control', :placeholder => 'Box Label' %>
				</div>
			</td>
		</tr>
	</table>

	<table class="form_table">
	  <tr> 
	    <td>
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Stat Box Query</label>
					<div id="editor"></div>
				</div>
			</td>
		</tr>
		<tr>
		  <td>
		  	The box query will be evaluated and the first cell in the result set will be displayed in the box. For information on the statistics tables created please see the <a href="https://github.com/no0p/plotpg">pgantenna statistics tables reference guide.
		  </td>
		</tr>
	</table>

  <textarea name="query" style="display: none;">
  </textarea>
	<br/>
  <%= submit_tag 'Create Stat Box', :class => 'btn btn-primary' %>

<% end %>



<%= render 'ace' %>

app/views/editor/new_plot.html.erb
<h4>New Plot Display</h4>
<br/><br/>
<%= form_tag create_plot_path, :class => 'bs-component' do %>
	
	<table class="form_table">
	  <tr>
	    <td>
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Title</label>
					<%= text_field_tag 'title', @plot.title, :class => 'form-control', :placeholder => 'Plot Title' %>
				</div>
			</td>
		</tr>
	</table>
	
	<table class="form_table">
	  <tr> 
	    <td>
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Width (% of row)</label>
					<%= text_field_tag 'width', @plot.width, :class => 'form-control', :placeholder => 'Width as % of window' %>
				</div>
			</td>
			<td class="last">	
				<div class="form-group" style="width: 300px;">
					<label class="control-label" for="focusedInput">Height (pixels)</label>
					<%= text_field_tag 'height', @plot.height, :class => 'form-control', :placeholder => 'Height in pixels' %>
				</div>
			</td>
		</tr>
	</table>

	<table class="form_table">
	  <tr> 
	    <td>
				<div class="form-group" style="">
					<label class="control-label" for="focusedInput">Plot Query</label><br/>
					<span class="form_message">The plot query is executed against the pgantenna database, and passed to the <a href="https://github.com/no0p/plotpg">plotpg</a> function with the resulting chart is displayed.</span><br/><br/>
					<div id="editor"></div>
				</div>
			</td>
		</tr>
	</table>
	
	<table class="form_table">
	  <tr> 
	    <td>
				<div class="form-group" style="">
					<label class="control-label" for="focusedInput">Gnuplot Commands</label><br/>
					<span class="form_message">Optional commands that are passed as the second parameter to the <a href="https://github.com/no0p/plotpg/wiki/Plotting-Data">plot function</a>.</span><br/><br/>
					<textarea name="gnuplot_commands" class="form-control"></textarea>
				</div>
			</td>
		</tr>
	</table>

  <textarea name="query" style="display: none;">
  </textarea>
	<br/>
  <%= submit_tag 'Create Plot', :class => 'btn btn-primary' %>

<% end %>



<%= render 'ace' %>